<?php
namespace root\kit;

//使用composer自动加载器
require 'vendor/autoload.php';

class LinkFactory
{
    //  echo \root\kit\LinkFactory::getLink('主页顶部公告');
    private static $LINK_STRINGS = array (
        // TOP
        '主页' => '/',
        '主页顶部公告' => '公告：欢迎来到华予健康服务平台！',
        '主页行业动态' => '#',
        '主页收藏本站' => '#',
        '主页关于我们' => '#',
        '主页代理商' => '#',
        'Login' => '/?cmd=Login',
        '验证图片下发' => '/?cmd=CreateVerImg',
        'LoginVer' => '/?cmd=LoginVer',
        'Logout' => '/?cmd=Logout',
        '注册' => '/?cmd=Register',
        '注册验证码下发' => '/?cmd=SendVerMessage&phone=',
        '注册验证' => '/?cmd=RegisterInsert',
        '忘记密码' => '/?cmd=ForgetPassword',
        '忘记密码_验证码验证发送AJAX' => '/?cmd=ForgetPasswordVerMessageSendAjax',
        '忘记密码_验证手机验证码' => '/?cmd=ForgetPassword&page=verifiphonecode',
        '忘记密码_验证码验证AJAX' => '/?cmd=ForgetPasswordVerifiAjax',
        '忘记密码_重置密码' => '/?cmd=ForgetPassword&page=resetpassword',
        '忘记密码_系统更新密码AJAX' => '/?cmd=ForgetPasswordUpdatePasswordAjax',
        '忘记密码_重置成功' => '/?cmd=ForgetPassword&page=forgetpasswordok',
        '修改订单状态为服务完成Ajax' => '/?cmd=SystemChangeIndentStatusEqualToCompleteServeAjax',
        '取消订单并提交取消理由Ajax' => '/?cmd=SystemNonPaymentIndentCancelAjax',
        '上传投诉信息Ajax'=>'/?cmd=SystemComplainSubmitAjax',
        '上传评论信息Ajax'=>'/?cmd=SystemCommentSubmitAjax',
        '系统修改邮箱Ajax' => '/?cmd=SystemEmailUpdateAjax',
        '修改密码验证码下发Ajax' => '/?cmd=ChangePasswordVerMessageSendAjax',
        '修改密码Ajax' => '/?cmd=ChangePasswordAjax',
        // 个人中心
        'Center' => '/?cmd=Center',
        '平台公告' => '/?cmd=ClientCenter&page=notice',
        '我的收藏' => '/?cmd=ClientCenter&page=collect',
        '客户订单记录' => '/?cmd=ClientCenter&page=orderlist',
        '客户订单详情' => '/?cmd=ClientCenter&page=indentdetails',
        '投诉_提交投诉' => '/?cmd=ClientCenter&page=complainsubmit',
        '投诉_投诉处理中' => '/?cmd=ClientCenter&page=complainverifi',
        '投诉_投诉处理完成' => '/?cmd=ClientCenter&page=complaincomplete',
        '评价_提交评价' => '/?cmd=ClientCenter&page=commentsubmit',
        '我的财富' => '/?cmd=ClientCenter&page=money',
        '我要兼职' => '/?cmd=ClientCenter&page=parttimejob',
        '客户申请成为服务商Ajax' => '/?cmd=SystemClientCenterSubmitVerifiForServer',
        '我的家庭成员' => '/?cmd=ClientCenter&page=myfamily',
        '我的家庭成员添加系统处理' => '/?cmd=SystemClientCenterFamilyInsert',
        '我的信息' => '/?cmd=ClientCenter&page=info',
        '我的信息修改' => '/?cmd=ClientCenter&page=infoupdate',
        '我的信息修改系统处理' => '/?cmd=SystemClientCenterDetailsUpdate',
        '修改密码' => '/?cmd=ClientCenter&page=changepassword',
        '绑定手机' => '/?cmd=ClientCenter&page=bindphone',
        '订阅邮件' => '/?cmd=ClientCenter&page=emailsubscription',
        '修改邮箱' => '/?cmd=ClientCenter&page=emailupdate',
        // 服务商个人中心
        '服务商平台公告' => '/?cmd=ServerCenter&page=notice',
        '服务商订单记录' => '/?cmd=ServerCenter&page=orderlist',
        '服务商订单详情' => '/?cmd=ServerCenter&page=indentdetails',
        '服务商投诉_提交投诉' => '/?cmd=ServerCenter&page=complainsubmit',
        '服务商投诉_投诉处理中' => '/?cmd=ServerCenter&page=complainverifi',
        '服务商投诉_投诉处理完成' => '/?cmd=ServerCenter&page=complaincomplete',
        '服务商评价_提交评价' => '/?cmd=ServerCenter&page=commentsubmit',
        '服务商我的服务' => '/?cmd=ServerCenter&page=servelist',
        '服务商修改订单状态为已完成服务Ajax' => '/?cmd=SystemServerChangeIndentStatusEqualToConfirmServeAjax',
        '服务商修改订单状态为完成退款Ajax' => '/?cmd=SystemServerChangeIndentStatusEqualToCompleteRefundAjax',
        '服务商修改服务状态为删除Ajax' => '/?cmd=SystemServerChangeServeStatusEqualToDeleteAjax',
        '服务商我的服务编辑列表' => '/?cmd=ServerCenter&page=editservelist',
        '服务商我的服务编辑表单' => '/?cmd=ServerCenter&page=editserve',
        '服务商我的服务修改服务ajax' => '/?cmd=SystemServerCenterEditServeAjax&servetype=',
        '服务商我的服务发布服务' => '/?cmd=ServerCenter&page=insertserve',
        '服务商我的服务发布服务_上门服务' => '/?cmd=ServerCenter&page=insertserve&inserttype=home',
        '服务商我的服务发布服务_到店服务' => '/?cmd=ServerCenter&page=insertserve&inserttype=shop',
        '服务商我的服务发布服务_电话服务' => '/?cmd=ServerCenter&page=insertserve&inserttype=phone',
        '服务商我的服务发布服务_在线服务' => '/?cmd=ServerCenter&page=insertserve&inserttype=on_line',
        '服务商我的服务发布服务ajax' => '/?cmd=SystemServerCenterInsertServeAjax&servetype=',
        '服务商我的服务服务记录列表' => '/?cmd=ServerCenter&page=serverecord',
        '服务商我的服务待取消服务列表' => '/?cmd=ServerCenter&page=servecancellist',
        '投诉客户_提交投诉' => '/?cmd=ServerCenter&page=complainclientsubmit',
        '投诉客户_投诉处理中' => '/?cmd=ServerCenter&page=complainclientverifi',
        '投诉客户_投诉处理完成' => '/?cmd=ServerCenter&page=complainclientcomplete',

        '服务商我的日程' => '/?cmd=ServerCenter&page=schedule',
        '服务商文章管理' => '/?cmd=ServerCenter&page=articlelist',
        '服务商文章插入' => '/?cmd=ServerCenter&page=articleinsert',
        '服务商文章插入系统操作Ajax' => '/?cmd=SystemServerCenterNewsInsertAjax',
        '服务商文章更新系统操作Ajax' => '/?cmd=SystemServerCenterNewsUpdateAjax',
        '服务商文章编辑' => '/?cmd=ServerCenter&page=articleedit',
        '服务商我的收藏' => '/?cmd=ServerCenter&page=collect',
        '服务商我的财富' => '/?cmd=ServerCenter&page=money',
        '服务商我的家庭成员' => '/?cmd=ServerCenter&page=myfamily',
        '我的家庭成员添加系统处理' => '/?cmd=SystemServerCenterFamilyInsert',
        '服务商我的信息' => '/?cmd=ServerCenter&page=info',
        '服务商我的信息修改' => '/?cmd=ServerCenter&page=infoupdate',
        '服务商我的信息修改系统处理' => '/?cmd=SystemServerCenterDetailsUpdate',
        '服务商认证管理' => '/?cmd=ServerCenter&page=verificationinfo',
        '服务商认证管理成功' => '/?cmd=ServerCenter&page=verificationinfook',
        '服务商认证管理修改页面' => '/?cmd=ServerCenter&page=verificationinfoupdate',
        '服务商认证信息修改Ajax' => '/?cmd=SystemServerCenterVerificationUpdate',
        '服务商修改密码' => '/?cmd=ServerCenter&page=changepassword',
        '服务商绑定手机' => '/?cmd=ServerCenter&page=bindphone',
        '服务商订阅邮件' => '/?cmd=ServerCenter&page=emailsubscription',
        '服务商修改邮箱' => '/?cmd=ServerCenter&page=emailupdate',

        // NAV
        '网站首页' => '/',
        '专家团队' => '/?cmd=MainServer',
        '专家团队详情页面' => '/?cmd=MainServer&page=details',
        '精品服务' => '/?cmd=MainServe',
        '健康科普' => '/?cmd=HealthScience',
        '社会公益' => '/?cmd=PublicBenefitList',
        '健康测试' => '/?cmd=TestList',
        '健康商城' => '#',
        // 主页相关页面
        '精品服务详情页面' => '/?cmd=MainServe&page=details',
        '精品服务列表loadAjax' => '/?cmd=MainServeListLoadAjax',
        '购买流程_购物车' => '/?cmd=ProcessOfPurchase&page=shoppingcart',
        '购买流程_单一服务订单' => '/?cmd=ProcessOfPurchase&page=singleorderconfirm',
        '用户PurchaseInsertAjax' => '/?cmd=SystemUserPurchaseInfoInsertAjax',
        '用户PurchaseDeleteAjax' => '/?cmd=SystemUserPurchaseInfoDeleteAjax',
        '提交服务订单AJAX' => '/?cmd=SystemIndentSubmitAjax',
        '提交充值AJAX' => '/?cmd=SystemTopUpSubmitAjax',
        '购买流程_选择支付方式' => '/?cmd=ProcessOfPurchase&page=confirmpayment',
        '购买流程_支付跳转' => '/?cmd=SystemIndentSendByCurl', // 在此设置支付入口
        '账户充值' => '/?cmd=ProcessOfPurchase&page=topupconfirm',
        '充值流程_选择支付方式' => '/?cmd=ProcessOfPurchase&page=topupconfirmpayment',
        '充值流程_支付跳转' => '/?cmd=SystemTopUpSendByCurl', // 在此设置支付入口
        '充值流程_支付宝跳回页面' => '/?cmd=ProcessOfPurchase&page=alipayreturn', // 在此设置支付入口
        // 新闻-专题-测试 相关
        'NewsDetails' => '/?cmd=NewsDetails&id=',
        'HearthTestDetails' => '/?cmd=HearthTestDetails&id=',
        'PublicBenefitDetails' => '/?cmd=PublicBenefitDetails&id=',
        'noticeDetails' => '/?cmd=NoticeDetails&id=',
        '健康生活方式专题页' => '/?cmd=HearthLifeSubject',
        '食疗养生中心专题页' => '/?cmd=HearthFoodSubject',
        '健康管理中心专题页' => '/?cmd=HearthManageSubject',
        '临床营养指导中心专题页' => '/?cmd=DoctorGuidanceSubject',
        '肿瘤防治中心专题页' => '/?cmd=TumourCureSubject',
        '心理健康咨询中心专题页' => '/?cmd=HearthMentalitySubject',
        '妇幼健康指导中心专题页' => '/?cmd=WomanGuidanceSubject',
        '新闻列表' => '?cmd=NewsList',
        'TestList' => '/?cmd=TestList',
        'TestDetails' => '/?cmd=TestDetails&id=',
        'TestResult' => '/?cmd=TestResult&id=',
        // admin-page
        'Home' => '/?cmd=Admin',
        'AdminLoginVerify' => '/?cmd=AdminLoginVerify',
        '订单管理' => '/?cmd=AdminIndentManage',
        '订单详细信息' => '/?cmd=AdminIndentManage&page=ManageDetails',
        '投诉管理' => '/?cmd=AdminComplainManage',
        '投诉详细信息' => '/?cmd=AdminComplainManage&page=ManageDetails',
        '投诉状态更变为已处理' => '/?cmd=AdminComplainManageChangeStatusComplainOver',
        '服务管理' => '/?cmd=AdminServeManage',
        '服务详细信息' => '/?cmd=AdminServeManage&page=ManageDetails&id=',
        '审核服务状态' => '/?cmd=AdminServeManage&page=ManageUpdateStatus&id=',
        '服务状态审核_审核通过' => '/?cmd=AdminServeUpdateStatus&status=shelves&id=',
        '服务状态审核_审核未通过' => '/?cmd=AdminServeUpdateStatus&status=not_pass&id=',
        '客户管理' => '/?cmd=AdminClientManage',
        '客户详细信息' => '/?cmd=AdminClientManage&page=ManageDetails&id=',
        '服务商管理' => '/?cmd=AdminServerManage',
        '服务商详细信息' => '/?cmd=AdminServerManage&page=ManageDetails&id=',
        '审核服务商状态' => '/?cmd=AdminServerManage&page=ManageUpdateStatus&id=',
        '服务商状态审核_审核通过' => '/?cmd=AdminServerUpdateVerification&status=pass&id=',
        '服务商状态审核_审核未通过' => '/?cmd=AdminServerUpdateVerification&status=not_pass&id=',


        'News' => '/?cmd=AdminNews&page=industryNews',
        'editNews' =>'/?cmd=EditNews&id=',
        'addNews' => '/?cmd=AddNews',
        'adminNewsAdd' => '/?cmd=AdminNewsAdd&type=',
        'NewsUpdate' => '/?cmd=AdminNewsUpdate&id=',
        'NewsDelect' => '/?cmd=AdminNewsDelete&id=',
        '行业新闻' => '/?cmd=AdminNews&page=industryNews',
        '公司新闻' => '/?cmd=AdminNews&page=companyNews',
        '健康生活方式' => '/?cmd=AdminNews&page=hearthLife',
        '食疗养生中心' => '/?cmd=AdminNews&page=hearthFood',
        '健康管理中心' => '/?cmd=AdminNews&page=hearthManage',
        '临床营养指导中心' => '/?cmd=AdminNews&page=doctorGuidance',
        '肿瘤防治中心' => '/?cmd=AdminNews&page=tumourCure',
        '心理健康咨询中心' => '/?cmd=AdminNews&page=hearthMentality',
        '妇幼健康指导中心' => '/?cmd=AdminNews&page=womanGuidance',
        '社会公益文章设置' => "/?cmd=AdminNews&page=publicBenefit",
        '基础文章设置' => '/?cmd=AdminNotice',
        '健康测试文章设置' => '/?cmd=AdminHearthTest',
        'editNotice' =>'/?cmd=EditNotice&id=',
        'NoticeUpdate' => '/?cmd=NoticeUpdate&id=',
        // 测试
        'addHearthTest' => '/?cmd=AddHearthTest',
        'editHearthTest' =>'/?cmd=EditHearthTest&id=',
        'adminHearthTestAdd' => '/?cmd=AdminHearthTestAdd',
        'HearthTestUpdate' => '/?cmd=AdminHearthTestUpdate&id=',
        'HearthTestDelect' => '/?cmd=AdminHearthTestDelete&id=',
        // 测试问题
        'HearthTestQuestion' => '/?cmd=AdminHearthTestQuestion&id=',
        'editHearthTestQuestion' => '/?cmd=EditHearthTestQuestion&id=',
        'adminHearthTestQuestionAdd' => '/?cmd=AdminHearthTestQuestionAdd&type=',
        'addHearthTestQuestion' => '/?cmd=AddHearthTestQuestion&type=',
        'HearthTestQuestionUpdate' => '/?cmd=AdminHearthTestQuestionUpdate&id=',
        'HearthTestQuestionDelect' => '/?cmd=AdminHearthTestQuestionDelete&id=',
        // 测试答案
        'HearthTestAnswer' => '/?cmd=AdminHearthTestAnswer&questionId=',
        'editHearthTestAnswer' => '/?cmd=EditHearthTestAnswer&id=',
        'addHearthTestAnswer' => '/?cmd=AddHearthTestAnswer',
        'adminHearthTestAnswerAdd' => '/?cmd=AdminHearthTestAnswerAdd',
        'HearthTestAnswerUpdate' => '/?cmd=AdminHearthTestAnswerUpdate&id=',
        'HearthTestAnswerDelete' => '/?cmd=AdminHearthTestAnswerDelete&',
        // 测试结果
        'HearthTestResult' => '/?cmd=AdminHearthTestResult&testId=',
        'editHearthTestResult' => '/?cmd=EditHearthTestResult&id=',
        'addHearthTestResult' => '/?cmd=AddHearthTestResult',
        'adminHearthTestResultAdd' => '/?cmd=AdminHearthTestResultAdd',
        'HearthTestResultUpdate' => '/?cmd=AdminHearthTestResultUpdate&id=',
        'HearthTestResultDelete' => '/?cmd=AdminHearthTestResultDelete&id=',
        // 系统管理
        '管理员设置' => '/?cmd=AdminManage',
        '添加一个新管理员' => '/?cmd=AdminManage&page=insert',
        '系统操作添加管理员AJAX' => '/?cmd=SystemInsertAdminAjax',
        // admin-page
    );

    private function __construct() {}

    static function getLink($str = 'Home')
    {
        if(empty($str)) {$str ="Home";}
        //将字符串转化为状态数
        return self::$LINK_STRINGS[$str];
    }

}